### PR TITLE
GET /is-auth Route Backend

### LINKED ISSUE #62: GET /is-Auth Route
#9 
- [x] **Route Name**

* full-route ` /is-Auth ` 
* method : `get` 
---- 

- [x] **Response**
- Success

```js
{ statusCode: 200, userData, isAuth: true }
```
- Failed
```js
{statusCode:401, message:"unautherized"}
```

### PR DESCRIPTION
**Pull request by Osama-you**
/is-auth: if the user is authed it will return the data({ id, name, avatar, role }) for that user

### CODE REVIEW

**Review by Ahmed-aed — APPROVED** [review]

**Review by mAbadsa — DISMISSED** [review]

**Review by zeinjendeya — DISMISSED** [review]

**Review by Ahmed-aed — DISMISSED** [review]

**Review by zeinjendeya — DISMISSED** [review]

**Review by Ahmed-aed — DISMISSED** [review]

**Review by mariamisa — DISMISSED** [review]

**Review by zeinjendeya — DISMISSED** [review]

**Review by Ahmed-aed — DISMISSED** [review]

**Review by zeinjendeya — DISMISSED** [review]

File: server/database/config/databaseConfig.sql [hunk 1]
```diff
@@ -0,0 +1,3 @@
+CREATE DATABASE servicedev;
+CREATE USER serviceuser WITH superuser password '123456';
+ALTER DATABASE servicedev OWNER TO serviceuser;
```
Comment (Ahmed-aed) [inline server/database/config/databaseConfig.sql:3]: what about this file ?

File: server/middleware/auth/checkToken.js [hunk 2]
```diff
@@ -5,7 +5,10 @@ const protectRoute = async (req, res, next) => {
   try {
     const { token } = req.cookies;
     const { id, role } = await promiseJWT(JWT.verify, token);
```
Comment (Ahmed-aed) [inline server/middleware/auth/checkToken.js:7]: should use one syntax of 'role' or 'rule'
